Check plugin configuration when changes occur
mattermost-community/mattermost-plugin-circleci pull request #83
Opened 2021-03-29 18:11 UTC by nathanaelhoun

## Changes

- [x] Check plugin configuration when it changes and at startup
    - [x] At Rest Encryption Key is defined (closes #81)
    - [x] Webhook Token is defined and does not contains a forwardslash (closes #45).
- [x] Plugin fails to start if a configuration error is detected
- [x] Added unit tests
- [x] Fix missing keys for values in `API.LogError()` calls (mentionned in #81) 

## Changelog

```
## Enhancements
- Plugin configuration is checked at startup, and plugin fails to start if an error is detected
```

2021-04-06 16:04 UTC, jfrerich requested changes
Thanks, @nathanaelhoun! I've got just a handfull of nitpicks!

2021-04-06 16:04 UTC, jfrerich commented on server/plugin/configuration.go
> +		return errors.New("please regenerate the Webhook Secret, it mustn't contains a '/'")
```suggestion
		return errors.New("please regenerate the Webhook Secret, it cannot contain a '/'")
```

2021-04-06 16:04 UTC, jfrerich commented on server/plugin/manifest.go
> +        "help_text": "The secret used to authenticate the webhook to Mattermost. Should not contain a forwardslash.",
```suggestion
        "help_text": "The secret used to authenticate the webhook to Mattermost. Should not contain a forward slash.",
```

2021-04-06 16:04 UTC, jfrerich commented on plugin.json
> +                "help_text": "The secret used to authenticate the webhook to Mattermost. Should not contain a forwardslash.",
```suggestion
                "help_text": "The secret used to authenticate the webhook to Mattermost. Should not contain a forward slash.",
```

2021-04-06 17:53 UTC, nathanaelhoun commented
Thanks for the review @jfrerich, suggestions applied :wink:

2021-04-06 20:45 UTC, jfrerich approved these changes
Thanks @nathanaelhoun!

2021-05-12 16:06 UTC, nathanaelhoun commented
Hi! Any news on this?

2021-05-18 13:45 UTC, hanzei commented
@nathanaelhoun Heads up that there is a merge conflict

2021-05-18 19:15 UTC, nathanaelhoun commented
Thanks for the heads-up @hanzei, there are now fixed!

2021-05-18 20:01 UTC, jfrerich commented
@nathanaelhoun!  We have been in a major crunch to release the apps framework and that pushed back some of the bounty plugin work. @DHaussermann do are you ok with mering this PR and testing post-merge, similar to what you suggested in https://github.com/mattermost/mattermost-plugin-circleci/pull/79?

2021-05-20 21:19 UTC, DHaussermann approved these changes
I agree with @jfrerich 

This is suitable to test post merge as part of release testing post-merge

LGTM!

2021-05-20 21:34 UTC, nathanaelhoun commented
Thanks for the review @jfrerich @DHaussermann. 
The apps framework looks really exciting :smile:

2021-05-20 21:34 UTC, merged